### ISSUE TITLE
Overhaul Logging to use Python Logging Package

### ISSUE THREAD

**Issue by Justintime50** [Justintime50/github-archive#12]
This project is currently using a home grown logger, instead we should be using the logging package and roll-over old logs.

**Acceptance Criteria**
- [x] Items are logged to console instead of printed with the appropriate logging level for the type of message it is
- [x] Logged messages are successfully saved to a file
- [x] Old log files are rolled over to conserve disk space
- [x] Log file names play nicely with all OS's (Windows especially)

**Comment by GonistLelatel** [comment]
I see error while running on windows.
Logger is using an invalid filename with ":" char.

![debug_image2](https://user-images.githubusercontent.com/45871624/90310582-72a82080-defb-11ea-9d34-cf520480b42d.png)

**Comment by Justintime50** [comment]
Windows is so difficult...

Thanks for submitting this too! I'll make sure the filename conforms to the Windows filename schema as I overhaul logging here soon.

**Comment by Justintime50** [comment]
@GonistLelatel I apologize for the delay on this, thanks for your patience! I've merged in `v3.0.0` which fixes this log name issue on Windows along with various other items. Please don't hesitate to reach out if you find more items that need to be addressed. Thanks again for taking the time to report this!
