### ISSUE TITLE
[discussion] is github-archive working on windows?

### ISSUE THREAD

**Issue by GonistLelatel** [Justintime50/github-archive#13]
Is github-archive working on windows with python 3.8?

* installed with instruction
* `pip3 install github-archive`

![debug_image](https://user-images.githubusercontent.com/45871624/90299088-5bd2e100-de9d-11ea-859a-8df2feea9917.png)

**Comment by Justintime50** [comment]
How interesting, it works if you build from source but not if you install from pip. I'll look into this and put up a fix shortly for a pip installation. I get a similar error on macOS.

Thanks for reporting this!

**Comment by Justintime50** [comment]
Hey @GonistLelatel, thanks again for opening this issue. I believe I have corrected the problem, tested this on macOS and it now works for me here, would love to hear if you run into other issues on Windows but I believe if you install the new version you should be all set.

Please note that the command to invoke the tool has also been corrected from `github_archive` to `github-archive`.
