### ISSUE TITLE
Possible to have the script include org members as well?

### ISSUE THREAD

**Issue by 8465231** [Justintime50/github-archive#20]
I finally got this script running in a docker (ended up finding a python docker with everything setup properly, was a nightmare trying to do that manually as someone still new to linux) and it is really great, much better then my old one.

Only thing I miss from my old script was it would not only crawl through the org but also include all the org members.

Is it possible to add this functionality to this script by chance?

This is the script I used to use: https://github.com/mazen160/GithubCloner

Thanks for your work on this, saves me a ton of time and no way I could do this myself.

**Comment by Justintime50** [comment]
I can look into adding this when I have a bit of extra time.

**Comment by Justintime50** [comment]
I've split off your second request on this issue into #25 for a "dry run" flag.

I'm leaning towards adding functionality similar to orgs where you could specify a list of users that you want to clone/pull repos for. On your end, you could easily get the list of org users to add to that list by first curling the GitHub API and then providing that list of users. This way it's more flexible but you can still do what you're asking about.

Also curious, why the switch to GitHub Archive from GitHubCloner?

**Comment by Justintime50** [comment]
This has been merged and will be included in the next major release (ETA, next couple weeks hopefully). Make sure to watch the project to know when it gets released!

**Comment by 8465231** [comment]
> 
> 
> I've split off your second request on this issue into #25 for a "dry run" flag.
> 
> I'm leaning towards adding functionality similar to orgs where you could specify a list of users that you want to clone/pull repos for. On your end, you could easily get the list of org users to add to that list by first curling the GitHub API and then providing that list of users. This way it's more flexible but you can still do what you're asking about.
> 
> Also curious, why the switch to GitHub Archive from GitHubCloner?

Sorry, didn't see a notification before. Honestly I kinda forgot why I switched. I tried like 5 different options back to back and all had issues in various flavors.

Yours had the least issues / easiest to fix issues and worked better.

I have 2 use cases for this.

1: Is for repos I need to keep updated

2: Is for repos I simply need to archive as part of my data hording, if I don't they could disappear at any moment, I just know it. lol

**Comment by 8465231** [comment]
> 
> 
> This has been merged and will be included in the next major release (ETA, next couple weeks hopefully). Make sure to watch the project to know when it gets released!

Great! Been too busy to work on any of this myself lately anyways but hoping to have some time next month to get this stuff updated.
