### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by benlangfeld** [Justintime50/github-archive#24]
The current latest release is buggy without #23. Could you release a new version from the current HEAD of main?

**Comment by Justintime50** [comment]
@benlangfeld thanks for reporting this! I absolutely meant to cut a release and include a few other goodies and then life ran away from me. I'm going to cut a new release with this bug fix alone and not wait since this is something you're needing to take advantage of sooner than later.

**Comment by Justintime50** [comment]
`v3.1.1` is now released with this bug fix included. Depending on your setup, you may need to start from scratch; however, GitHub has typically been nice and "redirected" requests for the `master` branch for example to the `main` branch (as an example).
