### ISSUE TITLE
Feature request - pull starred repositories

### ISSUE THREAD

**Issue by bybor** [Justintime50/github-archive#26]
I don't know how this fits into the picture, but I have a few starred repositories that I'll miss if they go away. 

Could you consider implementing `include starred repositories`?

**Comment by Justintime50** [comment]
I think this would be a great addition. I'll consider adding this in the next release I'm currently working on.

If you'd like to show your support for the project and incentivize me a bit, starring this project here is a great idea 😉

**Comment by Justintime50** [comment]
This has been merged and will be included in the next major release. Make sure to star or watch this project to keep an eye on when that gets released!
