### ISSUE TITLE
does not clone private repos

### ISSUE THREAD

**Issue by itm-dev-tj** [Justintime50/github-archive#4]
Private repos are not cloned. Looks like the curl call should look like this: 
```
curl -s -H "Authorization: token YOUR_TOKEN_HERE" "https://api.github.com/user/repos?per_page=100"
``` 
as posted in [this gist comment](https://gist.github.com/milanboers/f34cdfc3e1ad9ba02ee8e44dae8e093f#gistcomment-3222031)

**Comment by Justintime50** [comment]
Great find! Github Archive had working private organization repos but not personal ones. I've corrected the personal private repos - these will work now.
