### ISSUE TITLE
Add new CLI parameter for Github hostname

### ISSUE THREAD

**Issue by phanak-sap** [Justintime50/github-archive#41]
The second initialization option in the pyGithub readme

```
# Github Enterprise with custom hostname
g = Github(base_url="https://{hostname}/api/v3", login_or_token="access_token")
```

**Comment by Justintime50** [comment]
Thanks for submitting this idea! I've put up a PR to address this. Give me a day or two to think on the naming and ensure there isn't anything else I've missed and I can get this released.
