### ISSUE TITLE
Add `--exclude` and `--include` flags for repo filtering

### ISSUE THREAD

**Issue by BrieucKyo** [Justintime50/github-archive#43]
Hi, 
It would be nice to be able to change the download path with an argument, and also have an argument for a limit of repository.

**Comment by Justintime50** [comment]
Hey there, you can already specify a custom path by passing the `--location` flag (see README).

As for limiting the number of repos returned, what's the use case? I can't foresee that being super useful because it would just cut off at the arbitrary number chosen. Maybe I'm not understanding?

**Comment by BrieucKyo** [comment]
Oh sorry, my bad for the location argument aha !
For the limit argument I was thinking about a way to --clone or --pull with maybe the last tens repos created something like that. Also that would be nice to blacklist some repos that we wouldn't want to --clone or --pull.

**Comment by Justintime50** [comment]
I'm down to add something like an `--include` and `--exclude` flag that allows you to specify a comma separated list of repos to either use or not. 

As for the last nth repos, I'm finding it difficult to justify the feature as it could be confusing to users. The point of GitHub Archive is to grab most everything from a user or an org to make a full archive. Saying "get the last X number of repos created/updated" still doesn't seem super useful. If you open up a separate issue here so we can track that conversation/work separately I'll consider it.
