### ISSUE TITLE
Windows clone error

### ISSUE THREAD

**Issue by chelove4draste** [Justintime50/github-archive#46]
I tried to use this tool o clone the github profile, but got an error
The log and command:
`>github-archive -u "sberbank-ai" --clone

# GitHub Archive started...

# Making API calls to GitHub for user repos...

# Cloning missing user repos...

Failed to clone ai-academy-2019
Command '['git', 'clone', 'git@github.com:sberbank-ai/ai-academy-2019.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ai-academy-2019']' returned non-zero exit status 128.
Failed to clone DigiTeller
Command '['git', 'clone', 'git@github.com:sberbank-ai/DigiTeller.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\DigiTeller']' returned non-zero exit status 128.
Failed to clone classic-ai
Command '['git', 'clone', 'git@github.com:sberbank-ai/classic-ai.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\classic-ai']' returned non-zero exit status 128.
Failed to clone ai-journey-2019
Command '['git', 'clone', 'git@github.com:sberbank-ai/ai-journey-2019.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ai-journey-2019']' returned non-zero exit status 128.
Failed to clone digital_peter_aij2020
Command '['git', 'clone', 'git@github.com:sberbank-ai/digital_peter_aij2020.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\digital_peter_aij2020']' returned non-zero exit status 128.
Failed to clone combined_solution_aij2019
Command '['git', 'clone', 'git@github.com:sberbank-ai/combined_solution_aij2019.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\combined_solution_aij2019']' returned non-zero exit status 128.
Failed to clone DetIE
Command '['git', 'clone', 'git@github.com:sberbank-ai/DetIE.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\DetIE']' returned non-zero exit status 128.
Failed to clone Graph-Research
Command '['git', 'clone', 'git@github.com:sberbank-ai/Graph-Research.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\Graph-Research']' returned non-zero exit status 128.
Failed to clone fusion_brain_aij2021
Command '['git', 'clone', 'git@github.com:sberbank-ai/fusion_brain_aij2021.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\fusion_brain_aij2021']' returned non-zero exit status 128.
Failed to clone ControlledNST
Command '['git', 'clone', 'git@github.com:sberbank-ai/ControlledNST.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ControlledNST']' returned non-zero exit status 128.
Failed to clone data-science-journey-2017
Command '['git', 'clone', 'git@github.com:sberbank-ai/data-science-journey-2017.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\data-science-journey-2017']' returned non-zero exit status 128.
Failed to clone model-zoo
Command '['git', 'clone', 'git@github.com:sberbank-ai/model-zoo.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\model-zoo']' returned non-zero exit status 128.
Failed to clone holdem-challenge
Command '['git', 'clone', 'git@github.com:sberbank-ai/holdem-challenge.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\holdem-challenge']' returned non-zero exit status 128.
Failed to clone ner-bert
Command '['git', 'clone', 'git@github.com:sberbank-ai/ner-bert.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ner-bert']' returned non-zero exit status 128.
Failed to clone no_flood_with_ai_aij2020
Command '['git', 'clone', 'git@github.com:sberbank-ai/no_flood_with_ai_aij2020.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\no_flood_with_ai_aij2020']' returned non-zero exit status 128.
Failed to clone music-composer
Command '['git', 'clone', 'git@github.com:sberbank-ai/music-composer.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\music-composer']' returned non-zero exit status 128.
Failed to clone htr_datasets
Command '['git', 'clone', 'git@github.com:sberbank-ai/htr_datasets.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\htr_datasets']' returned non-zero exit status 128.
Failed to clone lastochka
Command '['git', 'clone', 'git@github.com:sberbank-ai/lastochka.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\lastochka']' returned non-zero exit status 128.
Failed to clone mchs-wildfire
Command '['git', 'clone', 'git@github.com:sberbank-ai/mchs-wildfire.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\mchs-wildfire']' returned non-zero exit status 128.
Failed to clone no_fire_with_ai_aij2021
Command '['git', 'clone', 'git@github.com:sberbank-ai/no_fire_with_ai_aij2021.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\no_fire_with_ai_aij2021']' returned non-zero exit status 128.
Failed to clone OCR-model
Command '['git', 'clone', 'git@github.com:sberbank-ai/OCR-model.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\OCR-model']' returned non-zero exit status 128.
Failed to clone railway_infrastructure_detection_aij2021
Command '['git', 'clone', 'git@github.com:sberbank-ai/railway_infrastructure_detection_aij2021.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\railway_infrastructure_detection_aij2021']' returned non-zero exit status 128.
Failed to clone Real-ESRGAN
Command '['git', 'clone', 'git@github.com:sberbank-ai/Real-ESRGAN.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\Real-ESRGAN']' returned non-zero exit status 128.
Failed to clone ruGPT3_essays
Command '['git', 'clone', 'git@github.com:sberbank-ai/ruGPT3_essays.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ruGPT3_essays']' returned non-zero exit status 128.
Failed to clone ru-gpts
Command '['git', 'clone', 'git@github.com:sberbank-ai/ru-gpts.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ru-gpts']' returned non-zero exit status 128.
Failed to clone ru-dolph
Command '['git', 'clone', 'git@github.com:sberbank-ai/ru-dolph.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ru-dolph']' returned non-zero exit status 128.
Failed to clone ruGPT3_demos
Command '['git', 'clone', 'git@github.com:sberbank-ai/ruGPT3_demos.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ruGPT3_demos']' returned non-zero exit status 128.
Failed to clone ru-dalle
Command '['git', 'clone', 'git@github.com:sberbank-ai/ru-dalle.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ru-dalle']' returned non-zero exit status 128.
Failed to clone ru-prompts
Command '['git', 'clone', 'git@github.com:sberbank-ai/ru-prompts.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ru-prompts']' returned non-zero exit status 128.
Failed to clone sber-swap
Command '['git', 'clone', 'git@github.com:sberbank-ai/sber-swap.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\sber-swap']' returned non-zero exit status 128.
Failed to clone ru-clip
Command '['git', 'clone', 'git@github.com:sberbank-ai/ru-clip.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\ru-clip']' returned non-zero exit status 128.
Failed to clone sdsj2018-automl
Command '['git', 'clone', 'git@github.com:sberbank-ai/sdsj2018-automl.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\sdsj2018-automl']' returned non-zero exit status 128.
Failed to clone wing
Command '['git', 'clone', 'git@github.com:sberbank-ai/wing.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\wing']' returned non-zero exit status 128.
Failed to clone StackMix-OCR
Command '['git', 'clone', 'git@github.com:sberbank-ai/StackMix-OCR.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\StackMix-OCR']' returned non-zero exit status 128.
Failed to clone sberocr
Command '['git', 'clone', 'git@github.com:sberbank-ai/sberocr.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\sberocr']' returned non-zero exit status 128.
Failed to clone sber-vq-gan
Command '['git', 'clone', 'git@github.com:sberbank-ai/sber-vq-gan.git', 'C:\\Users\\richard\\github-archive\\repos\\sberbank-ai\\sber-vq-gan']' returned non-zero exit status 128.
Cleaning up repos...

GitHub Archive complete! Execution time: 0:00:09.308107.`

Also, git clone https://github.com/sberbank-ai/sber-vq-gan.git works

**Comment by Justintime50** [comment]
Hey there,

This could be due to a couple different reasons. Did the saved logs provide anymore details? These can typically be found in the `github-archive` folder in your home dir. 

Typically git will return 128 when the user isn't authenticated, when the request took too long. Do you have an ssh key created and added to GitHub? Did you then start your ssh agent properly?

You could also try the `--https` flag which will bypass authentication but GitHub has a small rate limit for unauthenticated requests. If this works, it means it's most likely due to you not being authenticated to make calls to their API.

**Comment by chelove4draste** [comment]
> 

Hello, thank you for the answer, --https solved it
