### ISSUE TITLE
Suggestion: DEFAULT_LOCATION should be the user's current working directory, not ~/github-archive

### ISSUE THREAD

**Issue by lauzadis** [Justintime50/github-archive#48]
Thanks for making this great tool.

The [default location where github-archive will be stored](https://github.com/Justintime50/github-archive/blob/449e3ed907bf6f9f309bf8687eed7b98f905e58b/github_archive/constants.py#L6) is `~/github-archive`.

This is confusing and not documented anywhere. I was expecting my cloned repositories to appear in the current working directory if no `--location` parameter is provided. 

Let me know what you think.

**Comment by Justintime50** [comment]
Fair concern! I can't change the default location because that's now the expected spot for users; however, I can certainly clarify the docs!

**Comment by Justintime50** [comment]
This has been addressed via https://github.com/Justintime50/github-archive/commit/9f38a0a0c0f58fe3fa7b84f499539c6cf12c9afd.

It's now listed in the README and the help output of the tool. You can continue to override this default by passing the `--location` flag at runtime and specifying your current directory or other. Thanks for the suggestion!
