### ISSUE TITLE
token not working with users, is this by design? 

### ISSUE THREAD

**Issue by tg12** [Justintime50/github-archive#52]
Using the Token would only allow you to download your own repos, Is it possible to combine the users and a token to download other users repos? Am I misinterpreting the documentation here? 

I get the error 

`github.GithubException.RateLimitExceededException: 403 {"message": "API rate limit exceeded for xxxxxxxx. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", "documentation_url": "https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}`

**Comment by Justintime50** [comment]
The token should allow to clone/pull anyone's public repos if used correctly. Can you provide the command you ran so I can see your usage? (Please don't include your token)

**Comment by tg12** [comment]
Yeah, Awesome! Thanks so can confirm if you use https and token all it does it clone your own personal repos and then any user that you pass it gets this error ... 

`# Cloning missing personal repos...

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/github-archive", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github_archive/cli.py", line 191, in main
    GithubArchiveCli().run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github_archive/cli.py", line 187, in run
    github_archive.run()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/github_archive/archive.py", line 125, in run
    self.users.remove(self.authenticated_username)
ValueError: list.remove(x): x not in list
# GitHub Archive started...
`

**Comment by tg12** [comment]
ha! Phew I thought I was misreading the documentation. It's working as expected with token and without https flag and changed to org for me.

**Comment by tg12** [comment]
Thanks for your swift help and response! I'll close this.

**Comment by 8465231** [comment]
Was the patch for this ever released? I am still getting the same error. It works on my own repos but no one elses.

**Comment by Justintime50** [comment]
> Was the patch for this ever released? I am still getting the same error. It works on my own repos but no one elses.

What version of the tool are you using? What command are you running? Please do not include your token

**Comment by 8465231** [comment]
> What version of the tool are you using? What command are you running? Please do not include your token

I do not see a way to see the version? It was just installed today with pip3 though.

I was testing with this command

```github-archive -t token -p -u solokeys -v```

It gives this error

# Pulling changes to personal repos...
Traceback (most recent call last):
  File "/usr/local/bin/github-archive", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/github_archive/cli.py", line 191, in main
    GithubArchiveCli().run()
  File "/usr/local/lib/python3.11/site-packages/github_archive/cli.py", line 187, in run
    github_archive.run()
  File "/usr/local/lib/python3.11/site-packages/github_archive/archive.py", line 126, in run
    self.users.remove(self.authenticated_username)
ValueError: list.remove(x): x not in list

**Comment by 8465231** [comment]
opps, used the wrong user at first, updated the command with the correct user, got too many windows open lol.

**Comment by Justintime50** [comment]
So it's working as expected?

**Comment by 8465231** [comment]
> So it's working as expected?

No, still same issue, I just grabbed an org for the test at first instead of a user. I corrected it and then edited the above post.

Still refuses to download any user repos and crashes with the error above.

**Comment by Justintime50** [comment]
Will continue this convo on #55
