### ISSUE TITLE
Doesn't work if there are spaces in the location name

### ISSUE THREAD

**Issue by sketchbuch** [Justintime50/github-archive#58]
Thanks for Github Archive - it cloned all my repos in less time than git clones just one.

One thing I noticed is that the location can't have spaces. I tried enclosing the location in quotes but the effect is the same.

The terminal claims that everything was cloned succesfully but there is nothing at the location specified. This works:

`github-archive --users sketchbuch --clone --location ~/Archive/github-archive --token xxxxxx`

This does not:

`github-archive --users sketchbuch --clone --location "~/Archive/github-archive - 27-08-2023" --token xxxxxx`

If it did somehow work I have no idea where it clones everything to. There is nothing in ~/Archive and searching for github-archive - 27-08-2023 finds nothing in gnome files

**Comment by Justintime50** [comment]
Paths typically shouldn't have spaces, though we could potentially escape them. What operating system are you running the tool on?

**Comment by sketchbuch** [comment]
Ubuntu. I think if the filesystem lets users add spaces to file and folder names, it would be great if github archive could too.

**Comment by Justintime50** [comment]
Certainly! I've patched this in `v6.1.2`. Thanks for reporting this issue and helping improve the tool!
