### ISSUE TITLE
use search params

### ISSUE THREAD

**Issue by CodersInHoods** [Justintime50/github-archive#8]
How can I add filter params to clone repos that are matching my searching params?

**Comment by Justintime50** [comment]
@CodersInHoods can you provide me an example? You can pass in any owner on GitHub to clone their repos (yours, a friends, an organization, etc). GitHub Archive does not support the ability to search for a particular type of repo. It's meant to clone all of somebody's repos. Great for backing up all your repos or if you have a new computer and you need all your projects cloned.

**Comment by Justintime50** [comment]
Hey @CodersInHoods, I'm going to close this issue due to inactivity. Feel free to respond here with some more context and I can look into this for you. Thanks!
